# GitHub CI build pipeline for gmmePylib
name: gmmePylib package CI build

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ${{ vars.BUILD_RUNSON }}-${{ vars.BUILD_RUNSON_WINDOWS }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup python ${{ vars.BUILD_PYTHON_VER }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ vars.BUILD_PYTHON_VER }}
            
            - name: Check python version
              run: python --version

            - name: Run package creation
              run: |
                pip install poetry
                poetry build

            - name: Archive package
              uses: actions/upload-artifact@v4
              with:
                name: gmmePylib
                path: dist