name: Testing github actions

on:
    workflow_run: 
        branches: [main]
        
    push:
        branches: [main]

jobs:
    testing:
        runs-on: windows-latest
        steps:
            - run: echo "this is a test"